export const DELETE_PRODUCT="DELETE_PRODUCT";
export const ADD_PRODUCT="ADD_PRODUCT";
export const GET_PRODUCT_FROM_SHARAT="GET_PRODUCT_FROM_SHARAT";

export const ADD_USER="ADD_USER";
export const UPDATE_CURRENT_USER="UPDATE_CURRENT_USER";

export const SAVE_ORDER="SAVE_ORDER";
export const ADD_TO_CART="ADD_TO_CART";
export const DELETE_FROM_CART="DELETE_FROM_CART";
export const UPDATE_QTY_IN_CART="UPDATE_QTY_IN_CART";
export const GET_CART_FROM_SHARAT="GET_CART_FROM_SHARAT";



